---
title: "Assignment 1 2020"
author: "David Welch"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Under Modules | Data | Bikes on Canvas you have data on the number of people counted cycling in Auckland and the amount of rain. 

1.  If you try to convert the cycle count data to tidy format (which you don't have to do for this assignment, because it's hard), what is one obstacle you will encounter?

2. Compute the total number of cyclists counted for each day, and a suitable summary of the rainfall for each day, in the same data frame.

3. Draw suitable graphs to display how the number of cyclists varies over time, over season, over day of the week, and with rain

4. Fit a regression model to predict the number of cyclists from year, season, day of the week, and rain. 

5. Based on your graphs and model, does rain have a big impact on the number of people cycling in Auckland?

 

Upload your rmarkdown (.Rmd) file and the HTML or PDF output that it produces to Canvas. 