---
title: "326 Assignment 2"
author: "Hasnain Cheena"
date: "30/03/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(s20x)
```

```{r Data Input}
CO2.df = read.table('Cape Grim.CO2.quarterly.txt', header=TRUE) 

#create time series object
CO2.fit.ts = ts(CO2.df[1:75, ], frequency = 4, start=c(2000,1))
CO2.pred.ts = ts(CO2.df[76:79, ], frequency = 4, start=c(2018,4))
CO2.full.ts = ts(CO2.df, frequency=4, start=c(2000,1))

#setup Time
Time = 1:79
reduced.Time = 1:75
#observations 1 to 75 used to fit the model
#observations 76 to 79 used to test models
```


## Question 1
```{r Q1}
HW.fit = HoltWinters(CO2.fit.ts)
HW.fit

HW.pred = predict(HW.fit,n.ahead=4)
HW.pred

HW.RMSEP = sqrt(1/4*sum((CO2.pred.ts-HW.pred)^2))

plot(HW.fit, HW.pred, main="Cape Grim CO2 - Holt Winters", xlab="Year", ylab="Observed/Fitted CO2 (ppm)")
```
## Question 2
```{r Q2 - Moving Average}
#calculate and extract seasonal estimates
decomp.ma.CO2 = decompose(CO2.fit.ts)
#de-seasonalize 
ma.CO2.ts = CO2.fit.ts - decomp.ma.CO2$seasonal
plot(ma.CO2.ts, main="Moving average seasonally adjusted CO2 Cape Grim", xlab="Year", ylab="CO2 (ppm)")

#build normal model
CO2.fit = lm(ma.CO2.ts ~ reduced.Time)
plot.ts(residuals(CO2.fit)) #residuals show peaking and clustering thus indicating a break in trend around t=50

#change in trend at t=50
Time.break = c(rep(0,49), reduced.Time[50:75]-reduced.Time[50])
CO2.break.fit = lm(ma.CO2.ts ~ reduced.Time + Time.break)
plot.ts(residuals(CO2.break.fit)) #residuals show still show clustering
acf(residuals(CO2.break.fit)) #check for autocorrelation - significant autocorrelation so add lag response variable

#add lagged response variable
CO2.break.fit2 = lm(ma.CO2.ts[-1] ~ reduced.Time[-1]+Time.break[-1] + ma.CO2.ts[-75])
plot.ts(residuals(CO2.break.fit2)) #residuals are 0 mean with constant variance 
acf(residuals(CO2.break.fit2)) #still significant lag at lag(1) - best we can do so far
normcheck(CO2.break.fit2, shapiro.wilk = TRUE) #check normality - seems normal but need more information about shapiro-wilk p-value
summary(CO2.break.fit2)

#use model to forecast
ma.seasonal.estimates = decomp.ma.CO2$figure
#forecast 2018 Q4
t76.sa.pred = CO2.break.fit2$coefficients[1] + CO2.break.fit2$coefficients[2] * 76 + CO2.break.fit2$coefficients[3] * 76 + CO2.break.fit2$coefficients[4]  * ma.CO2.ts[75]
t76.pred = t76.sa.pred + ma.seasonal.estimates[4]
#forecast 2019 Q1
t77.sa.pred = CO2.break.fit2$coefficients[1] + CO2.break.fit2$coefficients[2] * 77 + CO2.break.fit2$coefficients[3] * 77 + CO2.break.fit2$coefficients[4]  * t76.sa.pred
t77.pred = t77.sa.pred + ma.seasonal.estimates[1]
#forecast 2019 Q2
t78.sa.pred = CO2.break.fit2$coefficients[1] + CO2.break.fit2$coefficients[2] * 78 + CO2.break.fit2$coefficients[3] * 78 + CO2.break.fit2$coefficients[4]  * t77.sa.pred
t78.pred = t78.sa.pred + ma.seasonal.estimates[2]
#forecast 2019 Q3
t79.sa.pred = CO2.break.fit2$coefficients[1] + CO2.break.fit2$coefficients[2] * 79 + CO2.break.fit2$coefficients[3] * 79 + CO2.break.fit2$coefficients[4]  * t78.sa.pred
t79.pred = t79.sa.pred + ma.seasonal.estimates[3]

#calculte RMSEP
ma.pred.df = data.frame(CO2=c(t76.pred,t77.pred,t78.pred,t79.pred))
ma.pred = ts(ma.pred.df, start=c(2018,4), frequency = 4)

#RMSEP
MA.RMSEP = sqrt(1/4*sum((CO2.pred.ts-ma.pred)^2))
```
```{r Q2 - STL}
#calculate and extract seasonal estimates
decomp.stl.CO2 = stl(CO2.fit.ts, s.window="periodic")
#de-seasonalize 
#extract seasonal
stl.CO2.ts = CO2.fit.ts - decomp.stl.CO2$time.series[,1]
plot(stl.CO2.ts, main="STL seasonally adjusted CO2 Cape Grim", xlab="Year", ylab="CO2 (ppm)")

#same model as MA
CO2.break.fit3 = lm(stl.CO2.ts[-1] ~ reduced.Time[-1]+Time.break[-1] + stl.CO2.ts[-75])
plot.ts(residuals(CO2.break.fit3)) #residuals are 0 mean with constant variance 
acf(residuals(CO2.break.fit3)) #still significant lag at lag(1) - best we can do so far
normcheck(CO2.break.fit3, shapiro.wilk = TRUE) #check normality - seems normal but need more information about shapiro-wilk p-value
summary(CO2.break.fit3)

#forecasting
stl.seasonal.estimates = decomp.stl.CO2$time.series
#forecast 2018 Q4
t76.sa.pred = CO2.break.fit3$coefficients[1] + CO2.break.fit3$coefficients[2] * 76 + CO2.break.fit3$coefficients[3] * 76 + CO2.break.fit3$coefficients[4]  * stl.CO2.ts[75]
t76.pred = t76.sa.pred + stl.seasonal.estimates[4,1]
#forecast 2019 Q1
t77.sa.pred = CO2.break.fit3$coefficients[1] + CO2.break.fit3$coefficients[2] * 77 + CO2.break.fit3$coefficients[3] * 77 + CO2.break.fit3$coefficients[4]  * t76.sa.pred
t77.pred = t77.sa.pred + stl.seasonal.estimates[1,1]
#forecast 2019 Q2
t78.sa.pred = CO2.break.fit3$coefficients[1] + CO2.break.fit3$coefficients[2] * 78 + CO2.break.fit3$coefficients[3] * 78 + CO2.break.fit3$coefficients[4]  * t77.sa.pred
t78.pred = t78.sa.pred + stl.seasonal.estimates[2,1]
#forecast 2019 Q3
t79.sa.pred = CO2.break.fit3$coefficients[1] + CO2.break.fit3$coefficients[2] * 79 + CO2.break.fit3$coefficients[3] * 79 + CO2.break.fit3$coefficients[4]  * t78.sa.pred
t79.pred = t79.sa.pred + stl.seasonal.estimates[3,1]

#calculte RMSEP
stl.pred.df = data.frame(CO2=c(t76.pred,t77.pred,t78.pred,t79.pred))
stl.pred = ts(stl.pred.df, start=c(2018,4), frequency = 4)

#RMSEP
STL.RMSEP = sqrt(1/4*sum((CO2.pred.ts-stl.pred)^2))

```

## Question 3 - Technical Notes

## Question 4
```{r Q4}
#best predicting model - holt winters model
#fit holt winters
HW.full.fit = HoltWinters(CO2.full.ts)

#predict
HW.full.pred = predict(HW.full.fit, n.ahead=4)
HW.full.pred
```
