---
title: "326 A1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Read in data
```{r data}
aud.df = read.csv("Data\\NZD To AUD.csv")
sunspot.df = read.csv("Data\\Monthly Sunspot.csv")
temp.df = read.csv("Data\\Average Monthly Temp Nottingham.csv") 
```

## Question 1
```{r NZD AUD rate}
#plot time vs exchange rate
aud.ts = ts(aud.df$Rate, frequency=12, start=c(1990,1))
plot(aud.ts, main="AUD to NZD Exchange Rate (Jan 1990 - March 2020)", 
xlab="Year",ylab="Monthly average exchange rate")

#STL decomposition
aud.stl = stl(aud.ts, s.window = "periodic")
plot(aud.stl)
```
## Question 2
```{r Sunspot Number}
#plot time vs exchange rate
sunspot.ts = ts(sunspot.df$sunspot.month, frequency=12, start=c(1749,1))
plot(sunspot.ts, main="Monthly Sunspot Numbers (1749 to 2013)", 
xlab="Year", ylab="Sunspot Numbers")


#STL decomposition
sunspot.stl = stl(sunspot.ts, s.window = "periodic")
plot(sunspot.stl)
```
## Question 3
```{r Monthly Temp}
#plot time vs exchange rate
temp.ts = ts(temp.df$nottem, frequency=12, start=c(1920,1))
plot(temp.ts, main="Monthly Temperature in Notthingman", 
xlab="Year", ylab="Temperature")


#STL decomposition
temp.stl = stl(temp.ts, s.window = "periodic")
plot(temp.stl)
```