---
title: "Stats 326 - Assignment 5"
author: "Hasnain Cheena"
date: "27/05/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(s20x)
```

```{r Data Setup, include=FALSE}
CO2.df = read.table('Cape Grim.CO2.quarterly.txt', header=TRUE) 

#create time series object
red.CO2.ts = ts(CO2.df[1:75, ], frequency = 4, start=c(2000,1))
pred.CO2.ts = ts(CO2.df[76:79, ], frequency = 4, start=c(2018,4))
full.CO2.ts = ts(CO2.df$CO2, frequency=4, start=c(2000,1))

#setup Time
Time = 1:79
reduced.Time = 1:75
#observations 1 to 75 used to fit the model
#observations 76 to 79 used to test models

#quarterly factor
Quarter = factor(rep(1:4,20)[-80])
reduced.Quarter = Quarter[1:75]

#time break setup
reduced.Time.break = c(rep(0,49), Time[50:75]-Time[50])
```

## Question 1

```{r Q1 - Fit}
#best fitting SARIMA
sarima.fit = arima(red.CO2.ts,order=c(0,1,1),
seasonal=list(order=c(0,1,1),period=4))
sarima.fit
```
```{r Q1 - Plot, echo=FALSE}
plot.ts(residuals(sarima.fit),main="Residual Series")

acf(residuals(sarima.fit))
```
