---
title: 'Stats 326: Assignment 3'
author: "Hasnain Cheena"
date: "16/04/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(s20x)
```

```{r Data Setup, echo=FALSE}
CO2.df = read.table('Cape Grim.CO2.quarterly.txt', header=TRUE) 

#create time series object
CO2.fit.ts = ts(CO2.df[1:75, ], frequency = 4, start=c(2000,1))
CO2.pred.ts = ts(CO2.df[76:79, ], frequency = 4, start=c(2018,4))
CO2.full.ts = ts(CO2.df$CO2, frequency=4, start=c(2000,1))

#setup Time
Time = 1:79
reduced.Time = 1:75
#observations 1 to 75 used to fit the model
#observations 76 to 79 used to test models

#quarterly factor
Quarter = factor(rep(1:4,20)[-80])
reduced.Quarter = Quarter[1:75]

#time break setup
Time.break = c(rep(0,49), Time[50:75]-Time[50])
```

## Question 1

```{r Question - Model Fit and Assumptions}
CO2.sf.fit = lm(CO2.fit.ts[-1] ~ reduced.Time[-1] + Time.break[-1 ]+ reduced.Quarter[-1] + CO2.fit.ts[-75])

#model summary
summary(CO2.sf.fit)

#normality check
normcheck(CO2.sf.fit,shapiro.wilk = TRUE)

#residual series plot
plot.ts(residuals(CO2.sf.fit), main="Residual Series")

#acf plot
acf(residuals(CO2.sf.fit), main="ACF Plot of Residual Series")
```
```{r Question - Forecasting}

#forecast 2018 Q4
t76.sf.pred = CO2.sf.fit$coefficients[1] + (CO2.sf.fit$coefficients[2] * 76) + (CO2.sf.fit$coefficients[3] * 26) + 
  (CO2.sf.fit$coefficients[6]*1) + (CO2.sf.fit$coefficients[7]*CO2.fit.ts[75])

#forecast 2019 Q1
t77.sf.pred = CO2.sf.fit$coefficients[1] + (CO2.sf.fit$coefficients[2] * 77) + (CO2.sf.fit$coefficients[3] * 27) + 
  (CO2.sf.fit$coefficients[7]*t76.sf.pred)

#forecast 2019 Q2
t78.sf.pred = CO2.sf.fit$coefficients[1] + (CO2.sf.fit$coefficients[2] * 78) + (CO2.sf.fit$coefficients[3] * 28) + 
  (CO2.sf.fit$coefficients[4]*1) + (CO2.sf.fit$coefficients[7]*t77.sf.pred)

#forecast 2019 Q3
t79.sf.pred = CO2.sf.fit$coefficients[1] + (CO2.sf.fit$coefficients[2] * 79) + (CO2.sf.fit$coefficients[3] * 29) + 
  (CO2.sf.fit$coefficients[5]*1) + (CO2.sf.fit$coefficients[7]*t78.sf.pred)

#results
results.sf.df = data.frame(Predictions=c(t76.sf.pred,t77.sf.pred,t78.sf.pred,t79.sf.pred))

#RMSEP
sf.pred.ts = ts(results.sf.df$Predictions, start=c(2018,4), frequency = 4)
sf.RMSEP = sqrt(1/4*sum((CO2.pred.ts-sf.pred.ts)^2))
sf.RMSEP
```

## Question 2


```{r Question 2 - Harmonic Models}
#cosine harmonic model

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
